<?php
	
	global $SEG_ONE,$SEG_TWO,$pg;
	ini_set('display_errors', 1);
	date_default_timezone_set('Africa/Accra');
	define('ROOTDOC' , dirname(__FILE__));
	define('DS' , DIRECTORY_SEPARATOR);
	define('CLASSFOLDER' , ROOTDOC.DS.'A_Class'.DS);
	define('CONTROLLERFOLDER' ,	ROOTDOC.DS.'A_Controller'.DS);
	define('CONTROLLERSQLFOLDER' , ROOTDOC.DS.'A_Controller_Sql'.DS);
	define('COREFOLDER' , ROOTDOC.DS.'A_Core'.DS);
	define('MENUFOLDER' , ROOTDOC.DS.'A_Menu'.DS);
	define('INCLUDEFOLDER' , ROOTDOC.DS.'A_Include'.DS);
	define('MODELFOLDER' ,	ROOTDOC.DS.'A_Model'.DS);
	define('RESULTFOLDER' ,	ROOTDOC.DS.'A_Result'.DS);
	define('INVOICEFOLDER' , ROOTDOC.DS.'A_Invoices'.DS);
	define('INTFILE' , COREFOLDER.DS.'init.php');
	define('ENGINEFILE' , CLASSFOLDER.'engine.php');
	define('CONNECTIONFILE' , CLASSFOLDER.'connection.php');
	define('REQUIREONCEFILE' , COREFOLDER.'requireonce.php');
	define('LOGININTFILE' ,	COREFOLDER.'logininit.php');
	define('LOGINFOLDER'  ,	 ROOTDOC.DS.'App_Login'.DS);
	define('HOMEFOLDER' , ROOTDOC.DS.'App_Home'.DS);
	define('HOMEFILE' ,	HOMEFOLDER.'app_octopus_home.php');
	define('HEADERFILE' , INCLUDEFOLDER.'header.php');
	define('HEADERSUBFILE' , INCLUDEFOLDER.'header_sub.php');
	define('FOOTERFILE'  , INCLUDEFOLDER.'footer.php');
	define('SUBMENUFILE'  ,	 INCLUDEFOLDER.DS.'submenu.php');
	define('USERFOLDER' , ROOTDOC.DS.'App_User'.DS);


	
	// 
	// 	
	// define('DOC_MAINMODEL'  ,	 MODELFOLDER.DS.'model.php');	
	// define('DOC_FOLDERS'  ,	 ROOTDOC.DS.'folders/');
	// define('DOC_RADIOLOGY_VIEW'  ,	 ROOTDOC.DS.'App_Radiology_View'.DS);
	// define('DOC_PHYSIOTHERAPY_VIEW'  ,	 ROOTDOC.DS.'App_Physiotherapy_View'.DS);
	// define('DOC_PATIENTFOLDER_VIEW'  ,	 ROOTDOC.DS.'App_PatientFolder_View'.DS);
	// define('DOC_WALKIN_VIEW'  ,	 ROOTDOC.DS.'App_Walkin_View'.DS);	
	// define('DOC_CASHIER_VIEW'  ,	 ROOTDOC.DS.'App_Cashier_View'.DS);
	// define('DOC_LAB_VIEW'  ,	 ROOTDOC.DS.'App_Laboratory_View'.DS);
	// define('DOC_RECORDS_VIEW'  ,	 ROOTDOC.DS.'App_Records_View'.DS);
	// define('DOC_STATS_VIEW'  ,	 ROOTDOC.DS.'pages_stats'.DS);
	// define('DOC_SETUP_VIEW'  ,	 ROOTDOC.DS.'App_Setup_View'.DS);
	// define('DOC_REPORTS_VIEW'  ,	 ROOTDOC.DS.'App_Report_View'.DS);
	// define('DOC_ADMIN_VIEW'  ,	 ROOTDOC.DS.'App_Admin_View'.DS);
	// define('DOC_ADMISSION_VIEW'  ,	 ROOTDOC.DS.'App_Admission_View'.DS);
	// define('DOC_CLAIMBILLING_VIEW'  ,	 ROOTDOC.DS.'App_ClaimBilling_View'.DS);
	// define('DOC_PROMOTION_VIEW'  ,	 ROOTDOC.DS.'App_Promotion_View'.DS);
	// define('DOC_GENERALSTORE_VIEW'  ,	 ROOTDOC.DS.'App_GeneralStore_View'.DS);
	// define('DOC_ATTACHMENT_VIEW'  ,	 ROOTDOC.DS.'App_Attachment_View'.DS);
	// define('DOC_PATIENTREVIEW_VIEW'  ,	 ROOTDOC.DS.'App_PatientReview_View'.DS);
	// define('DOC_PATIENTCONSULTATION_VIEW'  ,	 ROOTDOC.DS.'App_PatientConsultation_View'.DS);
	// define('DOC_PASTCONSULTATION_VIEW'  ,	 ROOTDOC.DS.'App_PatientConsultation_View'.DS);
	// define('DOC_NURSE_VIEW'  ,	 ROOTDOC.DS.'App_Nurse_View'.DS);
	// define('DOC_HOME_VIEW'  ,	 ROOTDOC.DS.'App_Home_view'.DS);
	// define('DOC_DEVICE_VIEW'  ,	 ROOTDOC.DS.'App_Device_View'.DS);
	// define('DOC_PHARMACY_VIEW'  ,	 ROOTDOC.DS.'App_Pharmacy_View'.DS);
	// define('DOC_PRICE_VIEW'  ,	 ROOTDOC.DS.'App_Price_View'.DS);
	// define('DOC_MEDICALREPORT_VIEW'  ,	 ROOTDOC.DS.'App_MedicalReport_View'.DS);
	// define('DOC_INCIDENCE_VIEW'  ,	 ROOTDOC.DS.'App_Incidence_View'.DS);
	// define('DOC_PATIENTSCHEME_VIEW'  ,	 ROOTDOC.DS.'App_PatientScheme_View'.DS);
	// define('DOC_PATIENT_VIEW'  ,	 ROOTDOC.DS.'App_Patient_View'.DS);
	// define('DOC_USER_MODEL'  ,	 ROOTDOC.DS.'App_User_Model'.DS);
	// define('DOC_USER_VIEW'  ,	 ROOTDOC.DS.'App_User_View'.DS);
	// define('DOC_TRANSACTIONCASH_CONTROLLER'  ,	 ROOTDOC.DS.'App_TransactionCash_Controller'.DS);
	// define('DOC_TRANSACTIONCASH_MODEL'  ,	 ROOTDOC.DS.'App_TransactionCash_Model'.DS);
	// define('DOC_TRANSACTIONCASH_VIEW'  ,	 ROOTDOC.DS.'App_TransactionCash_View'.DS);
	// define('DOC_TRANSACTIONINSURANCE_MODEL'  ,	 ROOTDOC.DS.'App_TransactionInsurance_Model'.DS);
	// define('DOC_TRANSACTIONINSURANCE_VIEW'  ,	 ROOTDOC.DS.'App_TransactionInsurance_View'.DS);
	// define('DOC_WALLET_CONTROLLER'  , ROOTDOC.DS.'App_Wallet_Controller'.DS);
	// define('DOC_WALLET_MODEL'  , ROOTDOC.DS.'App_Wallet_Model'.DS);
	// define('DOC_WALLET_VIEW'  ,	ROOTDOC.DS.'App_Wallet_View'.DS);
	// define('RADIOLOGYSETUP_MODEL'  , ROOTDOC.DS.'App_RadiologySetup_Model'.DS);
	// define('RADIOLOGYSETUP_VIEW'  ,	ROOTDOC.DS.'App_RadiologySetup_View'.DS);
	// define('INVESTIGATIONPLANSETUPMODEL'  , ROOTDOC.DS.'App_InvestigationPlan_Model'.DS);
	// define('INVESTIGATIONPLANSETUPVIEW'  ,	ROOTDOC.DS.'App_InvestigationPlan_View'.DS);
	// define('LABSMODEL' ,  ROOTDOC.DS.'App_Labs_Model'.DS);
	// define('LABSVIEW' , ROOTDOC.DS.'App_Labs_View'.DS);		
	// // define('DOC_'  ,	 ROOTDOC.DS.'pages_records'.DS);
	// // define('DOC_'  ,	 ROOTDOC.DS.'pages_records'.DS);
	// // define('MODELFOLDER_'  ,	 ROOTDOC.DS.'pages_records'.DS);
	// define('MODELFOLDER_PATIENT'  ,	 ROOTDOC.DS.'App_Patient_Model'.DS);
	// define('MODELFOLDER_PATIENTSCHEME'  ,	 ROOTDOC.DS.'App_PatientScheme_Model'.DS);
	// define('MODELFOLDER_INCIDENCE'  ,	 ROOTDOC.DS.'App_Incidence_Model'.DS);
	// define('MODELFOLDER_MEDICALREPORT'  ,	 ROOTDOC.DS.'App_MedicalReport_Model'.DS);
	// define('MODELFOLDER_PRICE'  ,	 ROOTDOC.DS.'App_Price_Model'.DS);
	// define('MODELFOLDER_PHARMACY'  ,	 ROOTDOC.DS.'App_Pharmacy_Model'.DS);
	// define('MODELFOLDER_DEVICE'  ,	 ROOTDOC.DS.'App_Device_Model'.DS);
	// define('MODELFOLDER_HOME'  ,	 ROOTDOC.DS.'App_Home_Model'.DS);
	// define('MODELFOLDER_PATIENTFOLDER'  ,	 ROOTDOC.DS.'App_PatientFolder_Model'.DS);
	// define('MODELFOLDER_PHYSIOTHERAPY'  ,	 ROOTDOC.DS.'App_Physiotherapy_Model'.DS);
	// define('MODELFOLDER_PASTCONSULTATION'  ,	 ROOTDOC.DS.'App_PastConsultation_Model'.DS);
	// define('MODELFOLDER_RADIOLOGY'  ,	 ROOTDOC.DS.'App_Radiology_Model'.DS);
	// define('MODELFOLDER_RECORDS'  ,	 ROOTDOC.DS.'App_Records_Model'.DS);
	// define('MODELFOLDER_PATIENTPAYMENTSCHEME'  ,	 ROOTDOC.DS.'App_PatientPaymentScheme_Model'.DS);
	// define('MODELFOLDER_GENSTORE'  ,	 ROOTDOC.DS.'App_GeneralStore_Model'.DS);
	// define('MODELFOLDER_ATTACHMENT'  ,	 ROOTDOC.DS.'App_Attachment_Model'.DS);
	// define('MODELFOLDER_PATIENTREVIEW'  ,	 ROOTDOC.DS.'App_PatientReview_Model'.DS);
	// define('MODELFOLDER_ADMIN'  ,	 ROOTDOC.DS.'App_Admin_Model'.DS);
	// define('MODELFOLDER_ADMISSION'  ,	 ROOTDOC.DS.'App_Admission_Model'.DS);
	// define('MODELFOLDER_CASHIER'  ,	 ROOTDOC.DS.'App_Cashier_Model'.DS);
	// define('MODELFOLDER_CLAIMBILLING'  ,	 ROOTDOC.DS.'App_ClaimBilling_Model'.DS);
	// define('MODELFOLDER_WALKIN'  ,	 ROOTDOC.DS.'App_Walkin_Model'.DS);
	// define('MODELFOLDER_LABORATORY'  ,	 ROOTDOC.DS.'App_Laboratory_Model'.DS);
	// define('MODELFOLDER_PROMOTION'  ,	 ROOTDOC.DS.'App_Promotion_Model'.DS);
	// define('MODELFOLDER_REPORT'  ,	 ROOTDOC.DS.'App_Report_Model'.DS);
	// define('MODELFOLDER_SETUP'  ,	 ROOTDOC.DS.'App_Setup_Model'.DS);
	// define('MODELFOLDER_STATS'  ,	 ROOTDOC.DS.'App_Stats_Model'.DS);
	// define('MODELFOLDER_PATIENTCONSULATION'  ,	 ROOTDOC.DS.'App_PatientConsultation_Model'.DS);
	// define('MODELFOLDER_NURSE'  ,	 ROOTDOC.DS.'App_Nurse_Model'.DS);	
	

        $cashpaymentmethodcode = '2ff5c97d7ccc5523a37c7559cdb9f717';
		$cashpaymentmethod = 'CASH';
		$mobilemoneypaymentmethodcode = 'd43cdab483a9c0f983fced3b5835a19a';
		$mobilemoneypaymentmethod = 'MOBILE MONEY';
		$privateinsurancecode = '6c5314f8ca64d89e437e0f459b246495';
		$privateinsurance = 'PRIVATE INSURANCE';
		$nationalinsurancecode = '55bf44c672dfa8850064af4a6bb9fd5d';
		$nationalinsurance = 'NHIS';
		$partnercompaniescode = 'e0e2103fc5a47cd834e77317da85d200';
		$partnercompanies = 'PARTNER COMPANIES';
		$chequescode = '4eed55144c7059977c96b530ff54476c';
		$cheques = 'CHEQUES';
		$creditcode = 'e021e6b0119935978d2cb335552a7c30';
		$credit  = 'CREDIT';
		$prepaidcode = '8ac84668e32cec5d346381c4d307669f';
		$prepaid  = 'PREPAID';

		$admissionservice = 'SER0012';
		$newfolder = 'SER0001';
		$consultationadult = 'SER0002';
		$consultationchildren = 'SER0003';
		$consultationreview = 'SER0004';
		$consultationnight = 'SER0005';
		$consultationfasttrack = 'SER0006';
		$consultationspecialist = 'SER0018';
		$consultationorthopediccomplaint = 'SER0020';
		$consultationothopedic = 'SER0023';
		$consultationothopedicreview = 'SER0024';
		$consultationothopedicexpats = 'SER0019';
		$appointmentservice = 'SER0028';
		$newfolderexpat = 'SER0029';
		$restingbloodsugar = 'SER0030';
		$xraylabreview = 'SER0031';
		$consultationobsgyne = 'SER0032';
		$consultationrheumatology = 'SER0033';
		$consultationrheumatologyfollowup = 'SER0034';
		$consultationinternalmedicine = 'SER0035';
		$consultationinternalmedicinefollowup = 'SER0036';
		$medicalreport = 'SER0037';
		$employmentmedicallocalreport = 'SER0038';
		$schoolmedicallocalreport = 'SER0039';
		$consultationprocedures = 'SER0040';
		$consultationrheumatologytopup = 'SER0041';
		$consultationrheumatologyfollowuptopup = 'SER0042';
		$consultationinternalmedicinetopup = 'SER0043';
		$consultationinternalmedicinefollowuptopup = 'SER0044';
		$consultationorthopedicspecilisttopup = 'SER0045';
		$consultationorthopedicspecilistfollouptopup = 'SER0046';
		
		$largewounddressing = 'SER0047';
		$mediumwounddressing = 'SER0048';
		$smallwounddressing = 'SER0049';
		$walkinservice = 'SER0051';
		$familymedicine = 'SER0052';
		$familymedicinefollowup = 'SER0053';
		$detentionthreehours = 'SER0054';
		$detentionfivehours = 'SER0055';
		$schoolmedicalforeignreport = 'SER0056';
		$employmentmedicalforeignreport = 'SER0057';
		$insurancemedicalreportlocal = 'SER0058';
		$insurancemedicalreportforeign = 'SER0059';
		$airevacuationmedicalreport  = 'SER0060';
		$medicalopinionlocalreport  = 'SER0061';
		$medicalopinionforeignreport  = 'SER0062';
		$physiofirstvisit  = 'SER0063';
		$physiofollowup  = 'SER0064';
		$physioacupuncturesinglesite  = 'SER0065';
		$physioacupuncturemultisite  = 'SER0066';
		$physiofullbodymassage  = 'SER0067';
		$physioreflexology  = 'SER0068';
		$reportfees  = 'SER0069';
		$physioultrasoundfirstvisit  = 'SER0070';
		$physioultrasoundfollowup  = 'SER0071';
		$physioultrasoundonly  = 'SER0072';
		$dieticanconsultations  = 'SER0073';
		$dieticanconsultationsreview  = 'SER0074';
		$onlineconsultations  = 'SER0075';
		$onlineconsultationsfollowup  = 'SER0076';
		$physiopromotion  = 'SER0078';
		define("LARGEWOUNDDRESSING", "SER0047");
		define("MEDIUMWOUNDDRESSING", "SER0048");
		define("SMALLWOUNDDRESSING", "SER0049");
		$bedrest  = 'SER0077';
		$firstaid  = 'SER0010';
		$vitalsservices  = 'SER0011';
		$injectionservice  = 'SER0021';
		$injectionserviceoutside  = 'SER0022';
		$vitals  = 'SER0011';
		
		$nursingservices = "$bedrest','$firstaid','$vitalsservices','$injectionservice','$injectionserviceoutside','$largewounddressing','$mediumwounddressing','$smallwounddressing','$restingbloodsugar";

		$patientqueueexcept = "$bedrest','$firstaid','$vitalsservices','$injectionservice','$injectionserviceoutside','$largewounddressing','$mediumwounddressing','$smallwounddressing','$restingbloodsugar','$newfolder','$physiofollowup','$physioacupuncturesinglesite','$physioacupuncturemultisite','$physiofullbodymassage','$physioreflexology','$physioultrasoundfollowup','$physioultrasoundonly','$physiofirstvisit','$physioultrasoundfirstvisit','$physiopromotion";
		$physioservices = "$physiofollowup','$physioacupuncturesinglesite','$physioacupuncturemultisite','$physiofullbodymassage','$physioreflexology','$physioultrasoundfollowup','$physioultrasoundonly','$physiofirstvisit','$physioultrasoundfirstvisit','$physiopromotion";

		$consultationserviceslist = "$consultationadult','$consultationothopedic','$consultationchildren','$consultationreview','$consultationnight','$consultationfasttrack','$consultationspecialist','$consultationorthopediccomplaint','$consultationothopedicreview','$consultationothopedicexpats','$xraylabreview','$consultationobsgyne','$consultationrheumatology','$consultationrheumatologyfollowup','$consultationinternalmedicine','$consultationinternalmedicinefollowup";
		$wounddressingsservices = "$largewounddressing','$mediumwounddressing','$smallwounddressing";

		$conlist = "$consultationadult','$consultationothopedic','$consultationchildren','$consultationreview','$consultationnight','$consultationfasttrack','$consultationspecialist','$consultationorthopediccomplaint','$consultationothopedicreview','$consultationothopedicexpats";

		$reveiwlist = "$consultationreview','$xraylabreview','$consultationothopedicreview','$consultationrheumatologytopup','$consultationrheumatologyfollowuptopup','$consultationinternalmedicinetopup','$consultationinternalmedicinefollowuptopup','$consultationorthopedicspecilisttopup','$consultationorthopedicspecilistfollouptopup','$physiofollowup','$physioacupuncturesinglesite','$physioacupuncturemultisite','$physiofullbodymassage','$physioreflexology','$physioultrasoundfollowup','$physioultrasoundonly','$dieticanconsultationsreview";
		$prepaidscheme = 'PREPAID WALLET';
		$cashdollar = '83170ce7eb402e36832be3573659b3fa';
		$cashdollar = '83170ce7eb402e36832be3573659b3fa';
		$depositcode = 100;
		$depositscheme = 'DEPOSIT ACCOUNT';

		$foreigninsurancecode = '5963993495768d73aef75f22acd61bb6';
		$foreigninsurance = 'FOREIGN';
		
		$servicerequestservice = "$consultationadult,$consultationothopedic";
	//	$servicerequestservice = "34";		
		
	//	$instcodenuc = 'HMIS100'; 
		$instcodenuc = 'HMS1000';

        // $pathed = 'folders/';
        // $resultspathed = 'results/'; 
		// $resultsotherpathed = '../nuc.octopusgh.com/results/'; 
        // $invoices = 'invoices/'; 
        $day = Date('Y-m-d');
	    $days = Date('Y-m-d H:i:s');
		
		$thearchivedate = date('Y-m-d', strtotime($day. ' - 35 days'));
		$pendingcount = 0;
	
	    $year =  date('Y');
        $thereviewday = date('Y-m-d', strtotime($day. ' - 10 days'));
        $theexpiryday = date('Y-m-d', strtotime($day. ' + 30 days'));
		$thezero = 0;
		$theone = 1;
		$thetwo = 2;
		$thethree = 3;
		$thefour = 4;
		$thefive = 5;
		$thesix = 6;
		$theseven = 7;
		$theeight = 8;
		$thenine = 9;
		$theten = 10;
		$thefailed = 0;
		$thepassed = 2;
		$theexisted = 1;	
		$theactive = 'ACTIVE';
		$theinactive = 'INACTIVE';
		$thevalid = 'VALID';
		$theinvalid = 'INVALID';
		$nowday = date('Y-m-d', strtotime(str_replace('-','/', $day)));
		
		// $pathed = 'folders/'; 
        // $pathed = '../apcsg_rentit_images/';
        global $mysqldbconnectss,$sub,$pagethings,$servicerequestservice,$currentuserspec,$pendingcount,$menuhandle,$ppa,$pa,$perc,$folder,$req,$totalamount,$companyname,$instcodenuc,$useraccesslevel,$keys,$form_key,$form_number,$view,$eventcode,$event,$action,$userlevel,$footer,$pg,$dbconn,$db,$currentuser,$currentusercode,$dd,$version,$usershort,$paystate,$userinst,$currentuserlevel,$currentusername,$currentshiftcode,$currentshift,$nu,$pageroute,$instcode,$searchitem,$insttill,$versiontype,$currentstaffpershift,$resultspathed,$selectedone,$selectedtwo,$view,$currentday,$currentmonth,$currentyear,$currentweek,$actions,$cashpaymentmethodcode,$mobilemoneypaymentmethodcode,$resultsotherpathed;	
        