<?php
	REQUIRE_ONCE 'app_octopus_config.php';	
	REQUIRE_ONCE (LOGININTFILE) ;
	REQUIRE_ONCE (CONTROLLERSQLFOLDER.'octopus_paymentscheme.php');
	REQUIRE_ONCE (CONTROLLERSQLFOLDER.'octopus_current.php');
	REQUIRE_ONCE (CONTROLLERSQLFOLDER.'octopus_patient_visit.php');
	REQUIRE_ONCE (CONTROLLERSQLFOLDER.'octopus_patient_procedures.php');
	REQUIRE_ONCE (CONTROLLERSQLFOLDER.'octopus_patient.php');
	REQUIRE_ONCE (CONTROLLERSQLFOLDER.'octopus_patient_billitem.php');
	REQUIRE_ONCE (CONTROLLERSQLFOLDER.'octopus_patient_billing.php');
	REQUIRE_ONCE (CONTROLLERSQLFOLDER.'octopus_patient_billingpayment.php');
	REQUIRE_ONCE (CONTROLLERSQLFOLDER.'octopus_patient_bill.php');
	REQUIRE_ONCE (CONTROLLERFOLDER.'A_Shift_Controller.php');
	REQUIRE_ONCE (CONTROLLERFOLDER.'A_Current_Controller.php');
	REQUIRE_ONCE (CONTROLLERFOLDER.'A_Locum_Controller.php');
	REQUIRE_ONCE (USERFOLDER.'A_SetupUserModel.php');
	
	
// 	REQUIRE_ONCE 'class/code.php';
// 	REQUIRE_ONCE 'class/lov.php';
// 	REQUIRE_ONCE 'class/userlogs.php';
// //	REQUIRE_ONCE 'class/crypt.php';
// 	REQUIRE_ONCE 'class/patients.php';
// 	REQUIRE_ONCE 'class/dashboard.php';
// 	REQUIRE_ONCE 'class/settings.php';
// 	REQUIRE_ONCE 'class/pricing.php';
// 	REQUIRE_ONCE 'class/navigation.php';
// //	REQUIRE_ONCE 'class/upload.php';
// 	REQUIRE_ONCE 'controller/mainsql.php';
		
// 	REQUIRE_ONCE 'controller/AaappRequestServiceController.php';
// 	//REQUIRE_ONCE 'controller/AaappWalletOperationController.php';
// 	//REQUIRE_ONCE 'controller/AaappWalletController.php';
// 	REQUIRE_ONCE 'controller/AaappMedicalReportController.php';
// 	REQUIRE_ONCE 'controller/AaappPatientReviewController.php';
// 	REQUIRE_ONCE 'controller/AaappPatientSelfRegistrationController.php';
// 	REQUIRE_ONCE 'controller/AaappRecieptController.php';	
// 	REQUIRE_ONCE (CONTROLLERFOLDER.'AaappResultAttachmentController.php');
	
// 	// REQUIRE_ONCE 'controller/PatientQueueController.php';
// 	REQUIRE_ONCE 'controller/RegistrationController.php';	
// 	REQUIRE_ONCE 'controller/CashierController.php';
// 	// REQUIRE_ONCE 'controller/PaymentSchemeController.php';
// 	REQUIRE_ONCE 'controller/FacilityController.php';
// 	REQUIRE_ONCE 'controller/NurseController.php';
// 	REQUIRE_ONCE 'controller/ConsultationController.php';
// 	REQUIRE_ONCE 'controller/PatientController.php';
// 	REQUIRE_ONCE 'controller/PatientComplainsController.php';
// 	REQUIRE_ONCE 'controller/PatientPhysicalExamController.php';
// 	REQUIRE_ONCE 'controller/PatientDiagnosisController.php';
// 	REQUIRE_ONCE 'controller/PatientTreatmentController.php';
// 	REQUIRE_ONCE 'controller/PatientPrescriptionController.php';
// 	REQUIRE_ONCE 'controller/PatientInvestigationController.php';
// 	REQUIRE_ONCE 'controller/LabsController.php';
// 	REQUIRE_ONCE 'controller/ScheduleController.php';
// 	REQUIRE_ONCE 'controller/SettingsController.php';
// 	REQUIRE_ONCE 'controller/AppointmentController.php';
// 	REQUIRE_ONCE 'controller/PharmacyController.php';
// 	REQUIRE_ONCE 'controller/RecordsController.php';
// 	REQUIRE_ONCE 'controller/SetupController.php';
// 	REQUIRE_ONCE 'controller/BillingController.php';
// 	REQUIRE_ONCE 'controller/PatientAdmissionController.php';
// 	REQUIRE_ONCE 'controller/ConsultationActionController.php';
// 	REQUIRE_ONCE 'controller/ConsultationActionReferalController.php';
// 	REQUIRE_ONCE 'controller/CashierPartnerPaymentController.php';
// 	//REQUIRE_ONCE 'controller/PatientReviewController.php';
// 	REQUIRE_ONCE 'controller/WalkinController.php';
// 	REQUIRE_ONCE 'controller/PrescriptionPlanController.php';
// 	REQUIRE_ONCE 'controller/SentoutController.php';
// 	REQUIRE_ONCE 'controller/RequestionController.php';
// 	REQUIRE_ONCE 'controller/StoresController.php';
// 	REQUIRE_ONCE 'controller/AdmissionActionController.php';
// 	REQUIRE_ONCE 'controller/PatientPhysioController.php';
// 	// REQUIRE_ONCE 'controller/CashierWalletController.php';
// 	REQUIRE_ONCE 'controller/CashierRefundsController.php';
// 	REQUIRE_ONCE 'controller/CashierRecieptController.php';
// 	REQUIRE_ONCE 'controller/PharmacyPrescripeController.php';
// 	REQUIRE_ONCE 'controller/PharmacyDeviceController.php';
// 	REQUIRE_ONCE 'controller/ProcedureController.php';
// 	REQUIRE_ONCE "controller/MedicationController.php";	
// 	REQUIRE_ONCE 'controller/PatientNotesController.php';
// 	REQUIRE_ONCE 'controller/AppSetupConsumableController.php';
// 	REQUIRE_ONCE 'controller/AppUsersLogsControllerSql.php';
// 	REQUIRE_ONCE 'controller/AaappPatientClaimController.php';
// 	REQUIRE_ONCE 'controller/AaappPatientInvestigationController.php';
		
// 	REQUIRE_ONCE 'controller/AppPatientsQueueController.php';
// 	REQUIRE_ONCE 'controller/AppPatientsVisitActionController.php';
// 	REQUIRE_ONCE 'controller/AppBillsProcessingController.php';
// 	// REQUIRE_ONCE 'controller/PatientPhysioController.php';
	
// 	// for the sql tables 
// 	REQUIRE_ONCE 'controllersql/.php';
// 	REQUIRE_ONCE 'controllersql/.php';
// 	REQUIRE_ONCE 'controllersql/.php';
// 	REQUIRE_ONCE 'controllersql/.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_servicesrequest.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_investigationrequest.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_prescriptions.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_devices.php';
// 	
// 	REQUIRE_ONCE 'controllersql/octopus_patients_medicalreports.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_credit.php';
// 	
// 	
// 	REQUIRE_ONCE 'controllersql/octopus_st_pricing.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_paymentschemes.php';
// 	REQUIRE_ONCE 'controllersql/.php';
// 	REQUIRE_ONCE 'controllersql/octopus_cashier_forex.php';
// 	REQUIRE_ONCE 'controllersql/octopus_cashier_summary.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_reciept.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_discounts.php';
// 	REQUIRE_ONCE 'controllersql/octopus_cashier_tills.php';	
// 	REQUIRE_ONCE 'controllersql/';
// 	
// 	REQUIRE_ONCE 'controllersql/octopus_patients_appointments.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_deaths.php';
// 	REQUIRE_ONCE 'controllersql/octopus_incidences.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_attachedresults.php';
// 	REQUIRE_ONCE 'controllersql/octopus_appointmentslots.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_referal.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_contacts.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_complains.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_consultations.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_consultations_archive.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_admissions.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_admissions_archive.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_diagnosis.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_consultations_outcome.php';
// 	REQUIRE_ONCE 'controllersql/octopus_serial.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_claims.php';
// 	REQUIRE_ONCE 'controllersql/octopus_claims_monthly.php';
// 	REQUIRE_ONCE 'controllersql/octopus_claims_scheme.php';
// 	REQUIRE_ONCE 'controllersql/octopus_claims.php';
// 	REQUIRE_ONCE 'controllersql/octopus_cashier_endofday.php';
// 	REQUIRE_ONCE 'controllersql/octopus_shifts.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_refund.php';
// 	REQUIRE_ONCE 'controllersql/octopus_cashier_partnerbills.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_allergy.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_vitals.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_management.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_oxygen.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_notes.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_physicalexam.php';
// 	REQUIRE_ONCE 'controllersql/octopus_handover.php';
// 	REQUIRE_ONCE 'controllersql/octopus_labplans.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_labtest.php';
// 	REQUIRE_ONCE 'controllersql/octopus_labplans_tests.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_medications.php';
// 	REQUIRE_ONCE 'controllersql/octopus_prescriptionplan_medication.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_devices.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_radiology.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_procedures.php';
// 	REQUIRE_ONCE 'controllersql/octopus_prescriptionplan.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_chronic.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_allergy.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_chronic.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_complains.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_physicalexam.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_physicalexam_updates.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_diagnosis.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_diagnosis_updates.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_complains_updates.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_notes_updates.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_vitals_diet.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_oxygen.php';
// 	REQUIRE_ONCE 'controllersql/octopus_stats_doctors.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_consumables.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_wounddressing.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_procedure_consumables.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_procedures_consumables.php';
// 	REQUIRE_ONCE 'controllersql/octopus_pharmacy_expiry.php';
// 	REQUIRE_ONCE 'controllersql/octopus_pharmacy_stockadjustment.php';
// 	REQUIRE_ONCE 'controllersql/octopus_batches.php';
// 	REQUIRE_ONCE 'controllersql/octopus_admin_services.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_generalitems.php';
// 	REQUIRE_ONCE 'controllersql/octopus_sale.php';
// 	REQUIRE_ONCE 'controllersql/octopus_saleitems.php';
// 	REQUIRE_ONCE 'controllersql/octopus_passvalues.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_year.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_nurse_notes.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_nurse_followup.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_glucosemonitor.php';
// 	REQUIRE_ONCE 'controllersql/octopuspatients_users.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_promotion.php';
// 	REQUIRE_ONCE 'controllersql/octopus_userformlog.php';
// 	REQUIRE_ONCE 'controllersql/octopus_user.php';
// 	REQUIRE_ONCE 'controllersql/octopus_usereventlog.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_walkin.php';
// 	REQUIRE_ONCE 'controllersql/octopus_patients_promotion.php';	
// 	REQUIRE_ONCE 'controllersql/octopus_patient_physio_treatment.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_radiology_type.php';
// 	REQUIRE_ONCE 'controllersql/octopus_admin_receiptdetails.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_investigation_plan.php';
// 	REQUIRE_ONCE 'controllersql/octopus_st_investigation_plan_list.php';
		
// 	REQUIRE_ONCE 'model/mainmodel.php';
// 	REQUIRE_ONCE 'model/model.php';

// 	REQUIRE_ONCE (MODELFOLDER_PASTCONSULTATION.'AaappPatientPastConsultationVitalsModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PASTCONSULTATION.'AaappPatientPastConsultationOutcomeModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PASTCONSULTATION.'AaappPatientPastConsultationComplainModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PASTCONSULTATION.'AaappPatientPastConsultationPhysicalExamsModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PASTCONSULTATION.'AaappPatientPastConsultationInvestigationModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PASTCONSULTATION.'AaappPatientPastConsultationDiagnosisModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PASTCONSULTATION.'AaappPatientPastConsultationPrescriptionModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PASTCONSULTATION.'AaappPatientPastConsultationDeviceModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PASTCONSULTATION.'AaappPatientPastConsultationProcedureModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PASTCONSULTATION.'AaappPatientPastConsultationNotesModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PASTCONSULTATION.'AaappPatientPastConsultationManagementModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PASTCONSULTATION.'AaappPatientPastConsultationWounddressingModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PASTCONSULTATION.'AaappPatientPastConsultationFollowupModel.php');

// 	REQUIRE_ONCE (DOC_WALLET_CONTROLLER.'AaappWalletController.php');
// 	REQUIRE_ONCE (DOC_WALLET_MODEL.'AaappWalletModel.php');

// 	REQUIRE_ONCE 'model/AaappFinacialReportsModel.php';
// 	REQUIRE_ONCE 'model/AaappPatientHandoverModel.php';
// 	REQUIRE_ONCE (MODELFOLDER_PATIENT.'AaappPatientDeathModel.php');
// 	REQUIRE_ONCE 'model/AaappPatientglucoseMonitorModel.php';
// 	REQUIRE_ONCE 'model/AaappPatientAllergyModel.php';
// 	REQUIRE_ONCE (MODELFOLDER_MEDICALREPORT.'AaappMedicalReportModel.php');
// 	REQUIRE_ONCE 'model/AaappPatientProcedureProcessingModel.php';
// 	REQUIRE_ONCE 'model/AaappPatientProcedureConsumablesModel.php';
// 	REQUIRE_ONCE 'model/AaappCancelledServicesModel.php';
// 	REQUIRE_ONCE 'model/AaappPatientNurseReferalModel.php';
// 	REQUIRE_ONCE (MODELFOLDER_PATIENTREVIEW.'AaappPatientReviewModel.php');
// 	REQUIRE_ONCE 'model/AaappPatientNurseServicesModel.php';
// 	REQUIRE_ONCE 'model/AaappSetupPromotionModel.php';
// 	REQUIRE_ONCE (MODELFOLDER_RECORDS.'AaappRequestServiceModel.php'); 
// 	REQUIRE_ONCE (MODELFOLDER_RECORDS.'AaappPatientRegistrationModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_RECORDS.'AaappPatientRegistrationSelfModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_RECORDS.'AppRecordsModel.php');

// 	REQUIRE_ONCE (MODELFOLDER_PATIENTPAYMENTSCHEME.'AaappPatientPaymentSchemeModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_ATTACHMENT.'AppAttachmentModel.php');
	
// 	REQUIRE_ONCE 'model/AppTransactionModel.php';
// 	REQUIRE_ONCE 'model/AaappPatientPromotionModel.php';
// 	REQUIRE_ONCE 'model/AaappPatientPromotionWalletModel.php';
// 		

// 	REQUIRE_ONCE  (MODELFOLDER_PATIENTFOLDER.'AaappPatientFolderModel.php');
// 	REQUIRE_ONCE  (MODELFOLDER_PATIENTFOLDER.'AaappPatientFolderVitalsModel.php');
// 	REQUIRE_ONCE  (MODELFOLDER_PATIENTFOLDER.'AaappPatientFolderOutcomeModel.php');
// 	REQUIRE_ONCE  (MODELFOLDER_PATIENTFOLDER.'AaappPatientFolderComplainModel.php');
// 	REQUIRE_ONCE  (MODELFOLDER_PATIENTFOLDER.'AaappPatientFolderPhysicalExamsModel.php');	
// 	REQUIRE_ONCE  (MODELFOLDER_PATIENTFOLDER.'AaappPatientFolderDiagnosisModel.php');
// 	REQUIRE_ONCE  (MODELFOLDER_PATIENTFOLDER.'AaappPatientFolderPrescriptionModel.php');
// 	REQUIRE_ONCE  (MODELFOLDER_PATIENTFOLDER.'AaappPatientFolderDeviceModel.php');
// 	REQUIRE_ONCE  (MODELFOLDER_PATIENTFOLDER.'AaappPatientFolderProcedureModel.php');
// 	REQUIRE_ONCE  (MODELFOLDER_PATIENTFOLDER.'AaappPatientFolderNoteModel.php');
// 	REQUIRE_ONCE  (MODELFOLDER_PATIENTFOLDER.'AaappPatientFolderManagementModel.php');
// 	REQUIRE_ONCE  (MODELFOLDER_PATIENTFOLDER.'AaappPatientFolderWounddressingModel.php');
// 	REQUIRE_ONCE  (MODELFOLDER_PATIENTFOLDER.'AaappPatientFolderFollowupModel.php');
// 	REQUIRE_ONCE  (MODELFOLDER_PATIENTFOLDER.'AaappPatientFolderInvestigationModel.php');

// 	REQUIRE_ONCE (MODELFOLDER_GENSTORE.'AppSetupNonmedicalStoresModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_GENSTORE.'AppSetupPriceNonmedicalStoreModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_GENSTORE.'AppSaleModel.php');

// 	REQUIRE_ONCE 'model/AaappPatientConsultationReportModel.php';
// 	REQUIRE_ONCE 'model/AaappNurseFollowupModel.php';
// 	REQUIRE_ONCE 'model/AaappNurseNotessModel.php';	

// 	REQUIRE_ONCE (MODELFOLDER_PHYSIOTHERAPY.'AaappPatientPhysiotherapyModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PHYSIOTHERAPY.'AaappPatientPhysiotherapyQueueModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PHYSIOTHERAPY.'AaappPatientPhysiotherapyAllergyModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PHYSIOTHERAPY.'AaappPatientPhysiotherapyTreatmentModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PHYSIOTHERAPY.'AaappPatientPhysiotherapyManagementModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PHYSIOTHERAPY.'AaappPatientPhysiotherapyDeviceModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PHYSIOTHERAPY.'AaappPatientPhysiotherapyPrescriptionModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PHYSIOTHERAPY.'AaappPatientPhysiotherapyDiagnosisModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PHYSIOTHERAPY.'AaappPatientPhysiotherapyInvestigationModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PHYSIOTHERAPY.'AaappPatientPhysiotherapyPhysicalExamsModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_PHYSIOTHERAPY.'AaappPatientPhysiotherapyOutcomeModel.php');

// 	REQUIRE_ONCE (RADIOLOGYSETUP_MODEL.'AaappSetupRadiologyModel.php');
// 	REQUIRE_ONCE (RADIOLOGYSETUP_MODEL.'AaappSetupPriceRadiologyModel.php');
// 	REQUIRE_ONCE (MODELFOLDER_RADIOLOGY.'AaappRadiologyModel.php');	

// 	REQUIRE_ONCE 'model/AppAppointmentModel.php';
// 	REQUIRE_ONCE 'model/patientConsultationModel.php';
// 	REQUIRE_ONCE 'model/cashierModel.php';	
// 	//REQUIRE_ONCE 'model/requestserviceModal.php';
// 	REQUIRE_ONCE 'model/paymentSchemeModel.php';
// 	REQUIRE_ONCE 'model/facilityModel.php';
// 	// REQUIRE_ONCE 'model/nursesModel.php';
// 	REQUIRE_ONCE 'model/patientsModel.php';
// 	REQUIRE_ONCE 'model/patientComplainsModel.php';
// 	//REQUIRE_ONCE 'model/patientPhysicaleExamsModel.php';
// 	REQUIRE_ONCE 'model/patientDiagnosisModel.php';
// 	REQUIRE_ONCE 'model/patientTreatmentModel.php';
// 	REQUIRE_ONCE 'model/patientPrescriptionModel.php';
// 	REQUIRE_ONCE 'model/patientInvestigationModel.php';
// 	// REQUIRE_ONCE 'model/AppPatientsDeathModel.php';
// 	// REQUIRE_ONCE 'model/labsModel.php';
// 	REQUIRE_ONCE 'model/scheduleModel.php';	
// 	REQUIRE_ONCE 'model/alertsModel.php';
// 	REQUIRE_ONCE 'model/settingsModel.php';
// 	REQUIRE_ONCE 'model/pharmacyModel.php';
// 	REQUIRE_ONCE 'model/recordsModel.php';
// 	REQUIRE_ONCE 'model/setupModel.php';
// 	REQUIRE_ONCE 'model/billingModel.php';	
// 	REQUIRE_ONCE 'model/patientConsultationActionModel.php';
// 	REQUIRE_ONCE 'model/cashierpartnerpaymentModel.php';
// 	REQUIRE_ONCE 'model/patientreviewModel.php';
// 	// REQUIRE_ONCE 'model/walkinModel.php';
// 	REQUIRE_ONCE 'model/archiveModel.php';
// 	REQUIRE_ONCE 'model/prescriptionplanModel.php';
// 	REQUIRE_ONCE 'model/sentoutModel.php';
// 	REQUIRE_ONCE 'model/requestionmodel.php';
// 	REQUIRE_ONCE 'model/storesmodel.php';
// 	REQUIRE_ONCE 'model/patientAdmissionActionModel.php';
// 	REQUIRE_ONCE 'model/patientPhysioModel.php';
// 	//REQUIRE_ONCE 'model/cashierWalletModel.php';
// 	REQUIRE_ONCE 'model/cashierRefundsModel.php';
// 	REQUIRE_ONCE 'model/cashierRecieptModel.php';
// 	REQUIRE_ONCE 'model/pharmacyPrescriptionsModel.php';
// 	REQUIRE_ONCE 'model/pharmacyDeviceModel.php';
// 	REQUIRE_ONCE 'model/patientProcedureModel.php';
// 	REQUIRE_ONCE "model/medicationModel.php";
// 	REQUIRE_ONCE 'model/patientNotesModel.php';	
// 	REQUIRE_ONCE 'model/AppSetupConsumablesModel.php';
// 	REQUIRE_ONCE 'model/AppPharmacyModel.php';
// 	REQUIRE_ONCE 'model/AppProcedureProcessingModel.php';
// 	REQUIRE_ONCE 'model/AppSetupPriceServicesModel.php';
// 	REQUIRE_ONCE 'model/AppSetupServicesModel.php';
// 	REQUIRE_ONCE 'model/AppSetupProcedureModel.php';
// 	REQUIRE_ONCE 'model/AppSetupPriceProcedureModel.php';
// 	REQUIRE_ONCE 'model/AppSetupLabsModel.php';
// 	REQUIRE_ONCE 'model/AppSetupPriceLabsModel.php';
// 	REQUIRE_ONCE 'model/AppSetupImagingModel.php';
// 	REQUIRE_ONCE 'model/AppSetupPriceImagingModel.php';
// 	REQUIRE_ONCE 'model/AppSetupMedicationsModel.php';
// 	REQUIRE_ONCE 'model/AppSetupPriceMedicationModel.php';
// 	REQUIRE_ONCE 'model/AppSetupPriceDevicesModel.php';
// 	REQUIRE_ONCE 'model/AppSetupPriceConsumablesModel.php';
// 	REQUIRE_ONCE 'model/AppSetupDevicesModel.php';
// 	REQUIRE_ONCE 'model/AppSetupBatchesModel.php';
// 	REQUIRE_ONCE 'model/AppEndofdayModel.php';
// 	REQUIRE_ONCE 'model/AppClaimsProcessingModel.php';
// 	REQUIRE_ONCE 'model/AppIncidenceModel.php';
// 	REQUIRE_ONCE 'model/AppForexModel.php';
// 	REQUIRE_ONCE 'model/AppRefundsModel.php';	
// 	REQUIRE_ONCE 'model/AppPatientsQueueModel.php';
// 	// REQUIRE_ONCE 'model/AppNurseServicesModel.php';	
// 	// REQUIRE_ONCE 'model/AppReviewModel.php';	
// 	REQUIRE_ONCE 'model/AppPatientAdmissionModel.php';
// 	REQUIRE_ONCE 'model/AppPatientVitalsModel.php';
// 	REQUIRE_ONCE 'model/AppNurseModel.php';
// 	REQUIRE_ONCE 'model/AppWardModel.php';
	
// 	REQUIRE_ONCE 'model/AppPatientVisitActionsModel.php';
// 	//REQUIRE_ONCE 'model/AppPatientComplainModel.php';
// 	REQUIRE_ONCE 'model/AppPatientsPhysicalExamsModel.php';	
	
// 	// date_default_timezone_set('Africa/Accra');	

// 	REQUIRE_ONCE (DOC_TRANSACTIONCASH_CONTROLLER.'AppCashTransactionController.php');
// 	REQUIRE_ONCE (DOC_TRANSACTIONCASH_MODEL.'AppCreditModel.php');
// 	REQUIRE_ONCE (DOC_TRANSACTIONCASH_MODEL.'AppCashTransactionModel.php');	
	
	
//	$dbconn = $connections->dbconnect();

?>


